"""
Django settings for myLubd project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from typing import Optional

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables from a .env file for local development
try:
    from dotenv import load_dotenv, find_dotenv
    load_dotenv(find_dotenv(), override=False)
except Exception:
    pass

# Security
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'your-default-secret-key')
DEBUG = os.getenv('DEBUG', 'True') in ('True', '1', 'true', 'yes')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Hosts and Security Settings
_default_allowed_hosts = [
    'localhost',
    '127.0.0.1',
    '[::1]',
    'pcms.live',
    'www.pcms.live',
    'django-backend',
    'backend',
    # Include with port for internal Docker communication
    'backend:8000',
    'django-backend:8000',
    'localhost:8000',
    '127.0.0.1:8000',
]
_env_allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS')
if _env_allowed_hosts:
    # Parse ALLOWED_HOSTS from environment variable
    # Support both comma and space separated values
    ALLOWED_HOSTS = [h.strip() for h in _env_allowed_hosts.replace(',', ' ').split() if h.strip()]
    # Always include essential hosts (with and without port)
    essential_hosts = ['backend', 'django-backend', 'localhost', '127.0.0.1']
    # Also add with common ports
    for host in essential_hosts:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
        # Add with port 8000 for internal Docker communication
        host_with_port = f"{host}:8000"
        if host_with_port not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host_with_port)
else:
    ALLOWED_HOSTS = _default_allowed_hosts

# Log the final ALLOWED_HOSTS for debugging
import logging
logger = logging.getLogger(__name__)
logger.info(f"ALLOWED_HOSTS configured as: {ALLOWED_HOSTS}")
# Google OAuth Settings
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')

# OAuth2 settings
OAUTH2_SETTINGS = {
    'GOOGLE': {
        'client_id': GOOGLE_CLIENT_ID,
        'client_secret': GOOGLE_CLIENT_SECRET,
        'auth_uri': 'https://accounts.google.com/o/oauth2/auth',
        'token_uri': 'https://oauth2.googleapis.com/token',
        'userinfo_uri': 'https://www.googleapis.com/oauth2/v3/userinfo',
    }
}

# Applications
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'myappLubd',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_filters'
]

# Conditionally add optional packages if available
if DEBUG:
    try:
        import debug_toolbar
        INSTALLED_APPS.append('debug_toolbar')
    except ImportError:
        pass

try:
    import dbbackup
    INSTALLED_APPS.append('dbbackup')
except ImportError:
    pass

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Move this up
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Conditionally add debug_toolbar middleware if available and in debug mode
if DEBUG:
    try:
        import debug_toolbar
        MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')
    except ImportError:
        pass

# URLs and WSGI
ROOT_URLCONF = 'myLubd.urls'
WSGI_APPLICATION = 'myLubd.wsgi.application'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database (read from environment; falls back to sane defaults)
DATABASES = {
    'default': {
        'ENGINE': os.getenv('SQL_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('SQL_DATABASE', os.getenv('POSTGRES_DB', 'mylubd_db')),
        'USER': os.getenv('SQL_USER', os.getenv('POSTGRES_USER', 'mylubd_user')),
        'PASSWORD': os.getenv('SQL_PASSWORD', os.getenv('POSTGRES_PASSWORD', '')),
        'HOST': os.getenv('SQL_HOST', os.getenv('POSTGRES_HOST', 'db')),
        'PORT': os.getenv('SQL_PORT', os.getenv('POSTGRES_PORT', '5432')),
    }
}

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Enable caching
USE_CACHE = True

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'myappLubd.auth.Auth0JWTAuthentication',     # Auth0 only
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Allow anonymous access in development mode only
        'rest_framework.permissions.AllowAny' if DEBUG else 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# Auth0 configuration (set via environment variables)
# Support multiple env var names and sensible fallbacks
_raw_auth0_audience = os.getenv('AUTH0_AUDIENCE')

def _normalize_auth0_audience(aud: Optional[str]) -> Optional[str]:
    if not aud:
        return None
    value = aud.strip().rstrip('/')
    # Fix common misconfiguration where base domain is used without /api
    if value in ('https://pcms.live', 'http://pcms.live', 'https://www.pcms.live'):
        return 'https://pcms.live/api'
    if value.endswith('/api'):
        return value
    try:
        from urllib.parse import urlparse
        host = urlparse(value).netloc
        path = urlparse(value).path
        if host.endswith('pcms.live') and (path == '' or path == '/'):
            return f"{value}/api"
    except Exception:
        pass
    return value

AUTH0_AUDIENCE = _normalize_auth0_audience(_raw_auth0_audience)

_auth0_domain = os.getenv('AUTH0_DOMAIN')
_auth0_issuer = os.getenv('AUTH0_ISSUER') or os.getenv('AUTH0_ISSUER_BASE_URL')

if not _auth0_domain and _auth0_issuer:
    try:
        from urllib.parse import urlparse
        _parsed = urlparse(_auth0_issuer)
        _auth0_domain = (_parsed.netloc or _auth0_issuer).replace('https://', '').replace('http://', '').strip('/')
    except Exception:
        _auth0_domain = (_auth0_issuer or '').replace('https://', '').replace('http://', '').strip('/') or None

AUTH0_DOMAIN = _auth0_domain
AUTH0_ISSUER = _auth0_issuer or (f"https://{AUTH0_DOMAIN}/" if AUTH0_DOMAIN else None)

# Auth0 Management API credentials for fetching user details
AUTH0_CLIENT_ID = os.getenv('AUTH0_CLIENT_ID')
AUTH0_CLIENT_SECRET = os.getenv('AUTH0_CLIENT_SECRET')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'SIGNING_KEY': SECRET_KEY,  # Use Django's SECRET_KEY for JWT signing
    'VERIFYING_KEY': None,  # Use symmetric signing
    'ALGORITHM': 'HS256',  # Use HMAC with SHA-256
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',  # JWT ID claim
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'UPDATE_LAST_LOGIN': True,  # Update last login time
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}

# CORS and CSRF

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Configuration
if DEBUG:
    # In development, disable CSRF for easier testing
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False
    CSRF_USE_SESSIONS = False
    # Optionally disable CSRF middleware entirely in development
    # MIDDLEWARE = [m for m in MIDDLEWARE if m != 'django.middleware.csrf.CsrfViewMiddleware']
else:
    # Production CSRF settings
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_USE_SESSIONS = True

# Static and Media Files
STATIC_URL = '/static/'
STATIC_ROOT = '/app/static'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/app/media'
# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module} {funcName} {lineno} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'detailed_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'WARNING',
    },
    'django': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'ERROR',
        'propagate': False,
    },
    'django.request': {
        'handlers': ['detailed_console'],
        'level': 'DEBUG' if DEBUG else 'WARNING',
        'propagate': False,
    },
    'django.security': {
        'handlers': ['detailed_console'],
        'level': 'DEBUG' if DEBUG else 'WARNING',
        'propagate': False,
    },
    'myappLubd.auth': {
        'handlers': ['detailed_console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
        'propagate': False,
    },
}

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT') or '587')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') or os.getenv('EMAIL_HOST_USER', 'no-reply@pcms.live')
SERVER_EMAIL = os.getenv('SERVER_EMAIL') or DEFAULT_FROM_EMAIL

# Base URL for links in emails (frontend site)
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'https://pcms.live')

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_TZ = True

# Default Primary Key Field Type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File Uploads
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB

_env_cors_origins = os.getenv('DJANGO_CORS_ORIGINS')
if _env_cors_origins:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _env_cors_origins.replace(',', ' ').split() if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "https://pcms.live",
        "https://www.pcms.live",
        "http://nextjs-frontend:3000",
    ]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
      "https://pcms.live",
    "https://www.pcms.live",
    "http://nextjs-frontend:3000",
     
]
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# Add these CORS settings

CORS_ORIGIN_ALLOW_ALL = False
CORS_PREFLIGHT_MAX_AGE = 86400
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/root/my_project/backend/backups/'}
DBBACKUP_CLEANUP_KEEP = 7
MEDIABACKUP_CLEANUP_KEEP = 7
