"""
Django settings for myLubd project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from typing import Optional
from urllib.parse import quote

from django.core.exceptions import ImproperlyConfigured

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent
# Load environment variables from a .env file for local development
try:
    from dotenv import load_dotenv, find_dotenv
    load_dotenv(find_dotenv(), override=False)
except Exception:
    pass

DEBUG = os.getenv('DEBUG', 'False') in ('True', '1', 'true', 'yes')

# A local-only fallback keeps the development Compose environment easy to use.
# Production must provide its own strong value and fails before Django starts if
# it is absent or resembles a development key.
_DEVELOPMENT_SECRET_KEY = 'your-default-secret-key'
_KNOWN_INSECURE_SECRET_KEYS = {
    _DEVELOPMENT_SECRET_KEY,
    'development-secret',
    'django-insecure-change-me',
}
_configured_secret_key = os.getenv('DJANGO_SECRET_KEY')

if DEBUG:
    SECRET_KEY = _configured_secret_key or _DEVELOPMENT_SECRET_KEY
else:
    if not _configured_secret_key:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be configured in production.'
        )
    if (
        _configured_secret_key in _KNOWN_INSECURE_SECRET_KEYS
        or len(_configured_secret_key) < 50
    ):
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY must be at least 50 characters and must not use a development fallback.'
        )
    SECRET_KEY = _configured_secret_key

# The production Nginx TLS vhost overwrites X-Forwarded-Proto before proxying
# requests, so clients cannot forge the header Django trusts here.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production Security Settings
if not DEBUG:
    # SSL/HTTPS Settings
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # Preload is irreversible at deployment timescales and requires every
    # current and future subdomain to be HTTPS-ready.
    SECURE_HSTS_PRELOAD = False
    
    # Cookie Security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Content Security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Hosts and Security Settings
_development_allowed_hosts = [
    'localhost',
    '127.0.0.1',
    '[::1]',
    'django-backend',
    'backend',
]
_env_allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS')
if _env_allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _env_allowed_hosts.replace(',', ' ').split() if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = _development_allowed_hosts
else:
    raise ImproperlyConfigured(
        'DJANGO_ALLOWED_HOSTS must explicitly list production hosts.'
    )

if not DEBUG and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        'DJANGO_ALLOWED_HOSTS cannot contain a wildcard in production.'
    )

# Log the final ALLOWED_HOSTS for debugging
import logging
logger = logging.getLogger(__name__)
logger.info(f"ALLOWED_HOSTS configured as: {ALLOWED_HOSTS}")
# Google OAuth Settings
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')

# OAuth2 settings
OAUTH2_SETTINGS = {
    'GOOGLE': {
        'client_id': GOOGLE_CLIENT_ID,
        'client_secret': GOOGLE_CLIENT_SECRET,
        'auth_uri': 'https://accounts.google.com/o/oauth2/auth',
        'token_uri': 'https://oauth2.googleapis.com/token',
        'userinfo_uri': 'https://www.googleapis.com/oauth2/v3/userinfo',
    }
}

# Custom User Model
AUTH_USER_MODEL = 'myappLubd.User'

# Applications
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'myappLubd',
    'corsheaders',
    'rest_framework_simplejwt',
    'django_filters'
]

# Conditionally add optional packages if available
if DEBUG:
    try:
        import debug_toolbar
        INSTALLED_APPS.append('debug_toolbar')
    except ImportError:
        pass

try:
    import dbbackup
    INSTALLED_APPS.append('dbbackup')
except ImportError:
    pass

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Move this up
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ✅ PERFORMANCE: Session optimization
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'  # Use cache + DB for sessions
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_SAVE_EVERY_REQUEST = False  # Only save when modified

# Conditionally add debug_toolbar middleware if available and in debug mode
if DEBUG:
    try:
        import debug_toolbar
        MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')
    except ImportError:
        pass

# URLs and WSGI
ROOT_URLCONF = 'myLubd.urls'
WSGI_APPLICATION = 'myLubd.wsgi.application'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# POSTGRES_PASSWORD is canonical for Compose so Django and PostgreSQL cannot
# silently diverge. SQL_PASSWORD remains supported for direct Django runtimes.
_INSECURE_DATABASE_PASSWORDS = {
    'admin',
    'changeme',
    'default',
    'mylubd_password',
    'password',
    'postgres',
    'secret',
}
_configured_database_password = (
    os.getenv('POSTGRES_PASSWORD') or os.getenv('SQL_PASSWORD')
)

if not _configured_database_password:
    raise ImproperlyConfigured(
        'POSTGRES_PASSWORD (or SQL_PASSWORD for direct Django execution) must be configured.'
    )

if (
    _configured_database_password.strip().casefold()
    in _INSECURE_DATABASE_PASSWORDS
):
    raise ImproperlyConfigured(
        'The database password must not use a predictable default.'
    )

# Database (all environments require an explicit password)
DATABASES = {
    'default': {
        'ENGINE': os.getenv('SQL_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('SQL_DATABASE', os.getenv('POSTGRES_DB', 'mylubd_db')),
        'USER': os.getenv('SQL_USER', os.getenv('POSTGRES_USER', 'mylubd_user')),
        'PASSWORD': _configured_database_password,
        'HOST': os.getenv('SQL_HOST', os.getenv('POSTGRES_HOST', 'db')),
        'PORT': os.getenv('SQL_PORT', os.getenv('POSTGRES_PORT', '5432')),
        # ✅ PERFORMANCE: Connection pooling
        'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
        'CONN_HEALTH_CHECKS': True,  # Verify connections before reusing
        # ✅ PERFORMANCE: PostgreSQL specific optimizations
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000'  # 30 second query timeout
        },
    }
}

# ✅ PERFORMANCE: Enhanced cache configuration with multiple levels
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'default-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 5000,  # ✅ PERFORMANCE: Increased cache size
            'CULL_FREQUENCY': 3,  # ✅ PERFORMANCE: Remove 1/3 of entries when max reached
        },
        'TIMEOUT': 300,  # ✅ PERFORMANCE: 5 minute default timeout
    },
    'api_cache': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'api-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 3000,
            'CULL_FREQUENCY': 4,
        },
        'TIMEOUT': 600,  # ✅ PERFORMANCE: 10 minutes for API responses
    }
}

# Enable caching
USE_CACHE = True

# Redis is an internal authenticated service even though the primary cache
# backend currently remains local-memory. This contract is shared by backend
# maintenance utilities and prevents unauthenticated future consumers.
_INSECURE_REDIS_PASSWORDS = {
    'admin',
    'changeme',
    'default',
    'password',
    'redis',
    'secret',
}
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD')
if not REDIS_PASSWORD:
    raise ImproperlyConfigured('REDIS_PASSWORD must be configured.')
if REDIS_PASSWORD.casefold() in _INSECURE_REDIS_PASSWORDS:
    raise ImproperlyConfigured(
        'REDIS_PASSWORD must not use a predictable value.'
    )
if len(REDIS_PASSWORD) < 16:
    raise ImproperlyConfigured(
        'REDIS_PASSWORD must contain at least 16 characters.'
    )
if not all(
    (character.isascii() and character.isalnum()) or character in '._~-'
    for character in REDIS_PASSWORD
):
    raise ImproperlyConfigured(
        'REDIS_PASSWORD must contain only URL-safe characters.'
    )
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost' if DEBUG else 'redis')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_DB = os.getenv('REDIS_DB', '1')
REDIS_URL = (
    f"redis://:{quote(REDIS_PASSWORD, safe='')}@"
    f'{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
)

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For DRF browsable API
        'myappLubd.auth.Auth0JWTAuthentication',     # Auth0 only
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Fallback
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Allow anonymous access in development mode only
        'rest_framework.permissions.AllowAny' if DEBUG else 'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# Auth0 configuration (set via environment variables)
# Support multiple env var names and sensible fallbacks
_raw_auth0_audience = os.getenv('AUTH0_AUDIENCE')

def _normalize_auth0_audience(aud: Optional[str]) -> Optional[str]:
    if not aud:
        return None
    value = aud.strip().rstrip('/')
    # Current Auth0 API identifier. Normalize the accidental /api suffix used
    # by an earlier deployment to the identifier configured in Auth0.
    if value in (
        'https://api.hotelcarepro.com',
        'https://api.hotelcarepro.com/api',
        'https://hotelcarepro.com',
        'http://hotelcarepro.com',
        'https://www.hotelcarepro.com',
        'https://hotelcarepro.com/api',
    ):
        return 'https://api.hotelcarepro.com'
    if value.endswith('/api'):
        return value
    try:
        from urllib.parse import urlparse
        host = urlparse(value).netloc
        path = urlparse(value).path
        if host.endswith('hotelcarepro.com') and (path == '' or path == '/'):
            return f"{value}/api"
    except Exception:
        pass
    return value

AUTH0_AUDIENCE = _normalize_auth0_audience(_raw_auth0_audience)

_auth0_domain = os.getenv('AUTH0_DOMAIN')
_auth0_issuer = os.getenv('AUTH0_ISSUER') or os.getenv('AUTH0_ISSUER_BASE_URL')

if not _auth0_domain and _auth0_issuer:
    try:
        from urllib.parse import urlparse
        _parsed = urlparse(_auth0_issuer)
        _auth0_domain = (_parsed.netloc or _auth0_issuer).replace('https://', '').replace('http://', '').strip('/')
    except Exception:
        _auth0_domain = (_auth0_issuer or '').replace('https://', '').replace('http://', '').strip('/') or None

AUTH0_DOMAIN = _auth0_domain
AUTH0_ISSUER = _auth0_issuer or (f"https://{AUTH0_DOMAIN}/" if AUTH0_DOMAIN else None)
AUTH0_CLAIM_NAMESPACE = os.getenv('AUTH0_CLAIM_NAMESPACE', 'https://hotelcarepro.com').rstrip('/')

# Auth0 Management API credentials for fetching user details
AUTH0_CLIENT_ID = os.getenv('AUTH0_CLIENT_ID')
AUTH0_CLIENT_SECRET = os.getenv('AUTH0_CLIENT_SECRET')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'SIGNING_KEY': SECRET_KEY,  # Use Django's SECRET_KEY for JWT signing
    'VERIFYING_KEY': None,  # Use symmetric signing
    'ALGORITHM': 'HS256',  # Use HMAC with SHA-256
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',  # JWT ID claim
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'UPDATE_LAST_LOGIN': True,  # Update last login time
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
}

# CORS and CSRF

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# CSRF Configuration (already set above in Production Security Settings)
if DEBUG:
    # In development, additional CSRF settings
    CSRF_COOKIE_HTTPONLY = False
    CSRF_USE_SESSIONS = False
else:
    # Production CSRF settings (CSRF_COOKIE_SECURE already set above)
    CSRF_COOKIE_HTTPONLY = True
    CSRF_USE_SESSIONS = True

# Static and Media Files
STATIC_URL = '/static/'
STATIC_ROOT = '/app/static'

MEDIA_URL = '/media/'
MEDIA_ROOT = '/app/media'
# Production sends an authorized internal redirect to the Nginx container,
# which mounts the same media volume. Tests/development stream through Django.
PROTECTED_MEDIA_USE_X_ACCEL = os.getenv(
    'PROTECTED_MEDIA_USE_X_ACCEL', 'true' if not DEBUG else 'false'
).lower() in ('true', '1', 'yes')
# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{levelname} {asctime} {module} {funcName} {lineno} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'detailed_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'WARNING',
    },
    'django': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'ERROR',
        'propagate': False,
    },
    'django.request': {
        'handlers': ['detailed_console'],
        'level': 'DEBUG' if DEBUG else 'WARNING',
        'propagate': False,
    },
    'django.security': {
        'handlers': ['detailed_console'],
        'level': 'DEBUG' if DEBUG else 'WARNING',
        'propagate': False,
    },
    'myappLubd.auth': {
        'handlers': ['detailed_console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
        'propagate': False,
    },
}

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT') or '587')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') or os.getenv('EMAIL_HOST_USER', 'no-reply@pcms.live')
SERVER_EMAIL = os.getenv('SERVER_EMAIL') or DEFAULT_FROM_EMAIL
# Recipients override for daily summary (comma-separated string)
DAILY_SUMMARY_RECIPIENTS = os.getenv('DAILY_SUMMARY_RECIPIENTS')

# Base URL for links in emails (frontend site)
FRONTEND_BASE_URL = os.getenv('FRONTEND_BASE_URL', 'https://pcms.live')

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_TZ = True

# Default Primary Key Field Type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File Uploads
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB

_env_cors_origins = os.getenv('DJANGO_CORS_ORIGINS')
if _env_cors_origins:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _env_cors_origins.replace(',', ' ').split() if o.strip()]
elif DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://nextjs-frontend:3000",
    ]
else:
    raise ImproperlyConfigured(
        'DJANGO_CORS_ORIGINS must explicitly list production origins.'
    )

_env_csrf_trusted_origins = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS')
if _env_csrf_trusted_origins:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip()
        for origin in _env_csrf_trusted_origins.replace(',', ' ').split()
        if origin.strip()
    ]
elif DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://nextjs-frontend:3000",
    ]
else:
    raise ImproperlyConfigured(
        'DJANGO_CSRF_TRUSTED_ORIGINS must explicitly list production origins.'
    )
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# Add these CORS settings

CORS_ORIGIN_ALLOW_ALL = False
CORS_PREFLIGHT_MAX_AGE = 86400
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/root/my_project/backend/backups/'}
DBBACKUP_CLEANUP_KEEP = 7
MEDIABACKUP_CLEANUP_KEEP = 7
