server {
    listen 80;
    listen [::]:80;
    server_name findvexa.com www.findvexa.com;

    return 301 https://findvexa.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name www.findvexa.com;

    ssl_certificate     /etc/nginx/ssl/findvexa-origin.crt;
    ssl_certificate_key /etc/nginx/ssl/findvexa-origin.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    return 301 https://findvexa.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name findvexa.com;

    ssl_certificate     /etc/nginx/ssl/findvexa-origin.crt;
    ssl_certificate_key /etc/nginx/ssl/findvexa-origin.key;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.2 TLSv1.3;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

    client_max_body_size 10M;

    location / {
        resolver 127.0.0.11 valid=30s ipv6=off;

        set $findvexa_web http://pickora-web:80;
        proxy_pass $findvexa_web;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;

        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }

    error_page 500 502 503 504 /50x.html;
}
