# Generated by Django 4.2.16 on 2025-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0004_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_preventivemaintenance',
            field=models.BooleanField(default=False),
        ),
    ]
