# Generated by Django 4.2.16 on 2025-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0005_job_is_preventivemaintenance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='myappLubd_j_status_4362b5_idx',
        ),
        migrations.AddField(
            model_name='property',
            name='is_preventivemaintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_preventivemaintenance',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at', 'is_preventivemaintenance'], name='myappLubd_j_status_34e61d_idx'),
        ),
    ]
