# Generated by Django 4.2.16 on 2025-05-05 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myappLubd', '0006_remove_job_myapplubd_j_status_4362b5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_id', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('custom_days', models.PositiveIntegerField(blank=True, help_text="Custom frequency in days, if frequency is set to 'custom'", null=True)),
                ('next_due_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('after_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_after_images', to='myappLubd.jobimage')),
                ('before_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_before_images', to='myappLubd.jobimage')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_preventive_maintenances', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='The related maintenance job', on_delete=django.db.models.deletion.CASCADE, related_name='preventive_maintenances', to='myappLubd.job')),
            ],
            options={
                'verbose_name': 'Preventive Maintenance',
                'verbose_name_plural': 'Preventive Maintenances',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['scheduled_date', 'next_due_date'], name='myappLubd_p_schedul_c00b19_idx'), models.Index(fields=['frequency'], name='myappLubd_p_frequen_df8db2_idx')],
            },
        ),
    ]
