# Generated by Django 4.2.16 on 2025-05-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0007_preventivemaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Topics associated with this preventive maintenance', related_name='preventive_maintenances', to='myappLubd.topic'),
        ),
    ]
