# Generated by Django 4.2.16 on 2025-05-08 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0008_preventivemaintenance_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='pmtitle',
            field=models.TextField(default='No title'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Image after maintenance', null=True, upload_to='maintenance_pm_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Image before maintenance', null=True, upload_to='maintenance_pm_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
    ]
