# Generated by Django 4.2.16 on 2025-05-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0009_preventivemaintenance_pmtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='job',
        ),
    ]
