# Generated by Django 4.2.16 on 2025-05-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0010_remove_preventivemaintenance_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('repair', 'Under Repair'), ('inactive', 'Inactive'), ('retired', 'Retired')], default='active', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preventive_maintenances', models.ManyToManyField(blank=True, related_name='machines', to='myappLubd.preventivemaintenance')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='myappLubd.property')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['machine_id'], name='myappLubd_m_machine_38264d_idx'), models.Index(fields=['status'], name='myappLubd_m_status_176f0c_idx')],
            },
        ),
    ]
