# Generated by Django 4.2.16 on 2025-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0011_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_google',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
