# Generated by Django 4.2.16 on 2025-05-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0012_userprofile_last_login_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myappLubd.job'),
        ),
    ]
