# Generated by Django 4.2.16 on 2025-08-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0002_add_jpeg_path_to_jobimage'),
        ('myappLubd', '0015_preventivemaintenance_procedure'),
    ]

    operations = [
    ]
