# Generated by Django 4.2.16 on 2025-08-19 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0016_merge_20250817_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='after_image_jpeg_path',
            field=models.CharField(blank=True, help_text='Path to JPEG version of the after image for PDF generation', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='before_image_jpeg_path',
            field=models.CharField(blank=True, help_text='Path to JPEG version of the before image for PDF generation', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded image file', null=True, upload_to='maintenance_job_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='after_image',
            field=models.ImageField(blank=True, help_text='Image after maintenance', null=True, upload_to='maintenance_pm_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Image before maintenance', null=True, upload_to='maintenance_pm_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
    ]
