# Generated by Django 4.2.16 on 2025-08-19 18:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myappLubd', '0017_preventivemaintenance_after_image_jpeg_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('steps', models.JSONField(default=list, help_text='List of maintenance steps')),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in minutes')),
                ('required_tools', models.TextField(blank=True, null=True)),
                ('safety_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Procedure',
                'verbose_name_plural': 'Maintenance Procedures',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='actual_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Actual time taken in minutes', null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes about the completion of the task', null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the maintenance task', max_length=20),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='quality_score',
            field=models.PositiveIntegerField(blank=True, help_text='Quality score from 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', help_text='Current status of the maintenance task', max_length=20),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_maintenance_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recurring', models.BooleanField(default=True)),
                ('next_occurrence', models.DateTimeField()),
                ('recurrence_pattern', models.JSONField(default=dict, help_text="Pattern for recurring maintenance (e.g., {'type': 'monthly', 'day': 15})")),
                ('last_occurrence', models.DateTimeField(blank=True, null=True)),
                ('total_occurrences', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='myappLubd.preventivemaintenance')),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='myappLubd.preventivemaintenance')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance History',
                'verbose_name_plural': 'Maintenance History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='myappLubd.preventivemaintenance')),
            ],
            options={
                'verbose_name': 'Maintenance Checklist Item',
                'verbose_name_plural': 'Maintenance Checklist Items',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='procedure_template',
            field=models.ForeignKey(blank=True, help_text='Template procedure for this maintenance task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='myappLubd.maintenanceprocedure'),
        ),
    ]
