# Generated by Django 4.2.16 on 2025-08-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0018_maintenanceprocedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Skill level required for this procedure', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenanceprocedure',
            name='steps',
            field=models.JSONField(default=list, help_text='List of maintenance steps in JSON format'),
        ),
    ]
