# Generated by Django 4.2.24 on 2025-09-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0021_merge_20250909_0901'),
    ]

    operations = [
        # This is a placeholder migration to fix the dependency issue
        # The actual operations from this migration have been moved to 0023_remove_job_idx_job_user_status_and_more
        # This file exists only to maintain migration history consistency
    ]