# Generated by Django 4.2.24 on 2025-09-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0022_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='idx_job_user_status',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='idx_job_pm_created',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='idx_job_updated_at',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_pm_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_defect_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobimage',
            name='idx_jobimage_job',
        ),
        migrations.RemoveIndex(
            model_name='jobimage',
            name='idx_jobimage_uploaded',
        ),
        migrations.RemoveIndex(
            model_name='machine',
            name='idx_machine_status',
        ),
        migrations.RemoveIndex(
            model_name='machine',
            name='idx_machine_property',
        ),
        migrations.RemoveIndex(
            model_name='machine',
            name='idx_machine_maintenance',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='idx_pm_scheduled',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='idx_pm_completed',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='idx_pm_frequency',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='idx_pm_status',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='idx_pm_created_by',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='pm_schedule_complete_idx',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='pm_freq_schedule_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_pm',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='idx_property_name',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='idx_room_type_active',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='idx_room_name',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='room_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='idx_userprofile_google',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='myappLubd_j_status_4362b5_idx',
            old_name='idx_job_status_created',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='myappLubd_j_status_c9b764_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='myappLubd_j_created_1c873c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['priority'], name='myappLubd_j_priorit_3a46fb_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_preventivemaintenance'], name='myappLubd_j_is_prev_2b6820_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user'], name='myappLubd_j_user_id_7d2d23_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['updated_by'], name='myappLubd_j_updated_b0c068_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['completed_at'], name='myappLubd_j_complet_439fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'status'], name='myappLubd_j_user_id_5bac13_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_preventivemaintenance', 'status'], name='myappLubd_j_is_prev_6618f4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at', 'status', 'priority'], name='myappLubd_j_created_d0b346_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'created_at'], name='myappLubd_j_user_id_32ad73_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'priority'], name='myappLubd_j_status_9e44a7_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['created_at'], name='job_pending_created_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('is_preventivemaintenance', True)), fields=['created_at'], name='job_pm_created_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('completed_at__isnull', False)), fields=['completed_at'], name='job_completed_at_idx'),
        ),
    ]
