# Generated by Django 4.2.24 on 2025-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0025_userprofile_property_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_defect_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='pm_schedule_complete_idx',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='pm_freq_schedule_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='room_name_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='images',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='property_id',
            field=models.CharField(blank=True, help_text='ID of the property this user belongs to', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='property_name',
            field=models.CharField(blank=True, help_text='Name of the property this user belongs to', max_length=255, null=True),
        ),
    ]
