# Generated by Django 4.2.24 on 2025-11-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0026_alter_user_options_remove_job_job_status_created_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='myappLubd_j_status_c9b764_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='myappLubd_j_is_prev_2b6820_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='myappLubd_j_user_id_7d2d23_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='myappLubd_j_updated_b0c068_idx',
        ),
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='machines',
            field=models.ManyToManyField(blank=True, help_text='Machines that use this maintenance procedure', related_name='maintenance_procedures', to='myappLubd.machine'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['updated_at'], name='myappLubd_j_updated_1425f3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobimage',
            index=models.Index(fields=['job'], name='myappLubd_j_job_id_adef21_idx'),
        ),
        migrations.AddIndex(
            model_name='jobimage',
            index=models.Index(fields=['uploaded_at'], name='myappLubd_j_uploade_4298cd_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['property'], name='myappLubd_m_propert_dfb252_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['name'], name='myappLubd_m_name_22502f_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['status', 'property'], name='myappLubd_m_status_be7501_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['last_maintenance_date'], name='myappLubd_m_last_ma_ca225c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceprocedure',
            index=models.Index(fields=['name'], name='myappLubd_m_name_723e88_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceprocedure',
            index=models.Index(fields=['difficulty_level'], name='myappLubd_m_difficu_f46bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceprocedure',
            index=models.Index(fields=['created_at'], name='myappLubd_m_created_c5a72c_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['pm_id'], name='myappLubd_p_pm_id_733657_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['completed_date'], name='myappLubd_p_complet_9bad05_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['scheduled_date', 'completed_date'], name='myappLubd_p_schedul_7ab1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['created_by'], name='myappLubd_p_created_dfedac_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['job'], name='myappLubd_p_job_id_6ac980_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_id'], name='myappLubd_p_propert_897b42_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['name'], name='myappLubd_p_name_63d54f_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_id'], name='myappLubd_r_room_id_690f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='myappLubd_r_name_05c0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'is_active'], name='myappLubd_r_room_ty_05212f_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['title'], name='myappLubd_t_title_95143a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='myappLubd_u_user_id_c6b0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['property_id'], name='myappLubd_u_propert_462a2a_idx'),
        ),
    ]
