# Generated by Django 4.2.24 on 2025-11-08 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0027_remove_job_myapplubd_j_status_c9b764_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceprocedure',
            options={'ordering': ['equipment', 'frequency', 'name'], 'verbose_name': 'Maintenance Task', 'verbose_name_plural': 'Maintenance Tasks'},
        ),
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Maintenance Schedule', 'verbose_name_plural': 'Maintenance Schedules'},
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='myappLubd_p_schedul_c00b19_idx',
        ),
        migrations.RemoveIndex(
            model_name='preventivemaintenance',
            name='myappLubd_p_frequen_df8db2_idx',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='machines',
        ),
        migrations.AddField(
            model_name='machine',
            name='brand',
            field=models.CharField(blank=True, help_text='Equipment brand/manufacturer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.CharField(blank=True, help_text='Equipment category/type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Equipment this maintenance task is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='myappLubd.machine'),
        ),
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('custom', 'Custom')], default='monthly', help_text='How often this task should be performed', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='responsible_department',
            field=models.CharField(blank=True, help_text='Department responsible for this task (e.g., Engineering, MEP Contractor)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to perform this maintenance schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks about this maintenance schedule', null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='installation_date',
            field=models.DateField(blank=True, help_text='Date when equipment was installed', null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceprocedure',
            name='description',
            field=models.TextField(help_text='Detailed description of the maintenance task'),
        ),
        migrations.AlterField(
            model_name='maintenanceprocedure',
            name='estimated_duration',
            field=models.CharField(default='0 mins', help_text="Estimated duration (e.g., '5 mins', '2 hours')", max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenanceprocedure',
            name='name',
            field=models.CharField(help_text='Task name/title', max_length=200),
        ),
        migrations.AlterField(
            model_name='maintenanceprocedure',
            name='steps',
            field=models.JSONField(blank=True, default=list, help_text='List of maintenance steps in JSON format'),
        ),
        migrations.AlterField(
            model_name='preventivemaintenance',
            name='procedure_template',
            field=models.ForeignKey(blank=True, help_text='Maintenance task this schedule is for (task_id in ER diagram)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_schedules', to='myappLubd.maintenanceprocedure'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['serial_number'], name='myappLubd_m_serial__0df909_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['brand'], name='myappLubd_m_brand_1c5d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['category'], name='myappLubd_m_categor_7964ef_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['location'], name='myappLubd_m_locatio_3d1950_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['category', 'status'], name='myappLubd_m_categor_4b4adb_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['installation_date'], name='myappLubd_m_install_ebff3e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceprocedure',
            index=models.Index(fields=['equipment'], name='myappLubd_m_equipme_eedfbd_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceprocedure',
            index=models.Index(fields=['frequency'], name='myappLubd_m_frequen_622242_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceprocedure',
            index=models.Index(fields=['responsible_department'], name='myappLubd_m_respons_c0a8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceprocedure',
            index=models.Index(fields=['equipment', 'frequency'], name='myappLubd_m_equipme_d7be07_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['procedure_template'], name='myappLubd_p_procedu_1f0d97_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['assigned_to'], name='myappLubd_p_assigne_b60d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['status'], name='myappLubd_p_status_1432e9_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['scheduled_date'], name='myappLubd_p_schedul_bd388d_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['status', 'assigned_to'], name='myappLubd_p_status_0e3991_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivemaintenance',
            index=models.Index(fields=['procedure_template', 'status'], name='myappLubd_p_procedu_2c2d62_idx'),
        ),
    ]
