# Generated by Django 4.2.26 on 2025-11-08 06:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0028_alter_machine_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTaskImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], help_text='Type of image (Before or After)', max_length=10)),
                ('image_url', models.ImageField(help_text='Image file', upload_to='maintenance_task_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])])),
                ('jpeg_path', models.CharField(blank=True, help_text='Path to JPEG version of the image for PDF generation', max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Maintenance task this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='task_images', to='myappLubd.maintenanceprocedure')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_task_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Task Image',
                'verbose_name_plural': 'Maintenance Task Images',
                'ordering': ['task', 'image_type', '-uploaded_at'],
                'indexes': [models.Index(fields=['task'], name='myappLubd_m_task_id_0104cf_idx'), models.Index(fields=['image_type'], name='myappLubd_m_image_t_252a1f_idx'), models.Index(fields=['uploaded_at'], name='myappLubd_m_uploade_a4012b_idx'), models.Index(fields=['task', 'image_type'], name='myappLubd_m_task_id_9bb14d_idx')],
            },
        ),
    ]
