# Generated by Django 4.2.26 on 2025-11-08 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0029_maintenancetaskimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='after_image',
            field=models.ImageField(blank=True, help_text='After image for this maintenance task', null=True, upload_to='maintenance_task_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='after_image_jpeg_path',
            field=models.CharField(blank=True, help_text='Path to JPEG version of the after image for PDF generation', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='before_image',
            field=models.ImageField(blank=True, help_text='Before image for this maintenance task', null=True, upload_to='maintenance_task_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='before_image_jpeg_path',
            field=models.CharField(blank=True, help_text='Path to JPEG version of the before image for PDF generation', max_length=500, null=True),
        ),
    ]
