# Generated by Django 4.2.26 on 2025-11-09 13:14

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


class RemoveFieldStateOnly(Operation):
    """
    Removes a field from Django's migration state without touching the database.
    Safe to call multiple times because it simply pops the field if present.
    This is needed to handle cases where fields may have already been removed.
    """

    reduces_to_sql = False
    reversible = False

    def __init__(self, model_name, name):
        self.model_name = model_name
        self.name = name
        self.model_name_lower = model_name.lower()

    def state_forwards(self, app_label, state):
        model_key = (app_label, self.model_name_lower)
        model_state = state.models.get(model_key)
        if not model_state:
            return
        # Safely remove field if it exists
        if self.name in model_state.fields:
            model_state.fields.pop(self.name)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Database operations handled separately if needed
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # Not reversible
        pass

    def describe(self):
        return f"State-only removal of field {self.name} from {self.model_name}"


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0030_maintenanceprocedure_after_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'verbose_name': 'Recurring Schedule', 'verbose_name_plural': 'Recurring Schedules'},
        ),
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Preventive Maintenance', 'verbose_name_plural': 'Preventive Maintenance'},
        ),
        # Use safe RemoveFieldStateOnly to handle cases where fields may have already been removed
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Database columns will be removed by later migrations if needed
            state_operations=[
                RemoveFieldStateOnly('maintenanceprocedure', 'after_image'),
                RemoveFieldStateOnly('maintenanceprocedure', 'after_image_jpeg_path'),
                RemoveFieldStateOnly('maintenanceprocedure', 'before_image'),
                RemoveFieldStateOnly('maintenanceprocedure', 'before_image_jpeg_path'),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(blank=True, help_text='Unique machine identifier (auto-generated if left empty)', max_length=50, unique=True),
        ),
    ]
