# Generated by Django 4.2.24 on 2025-11-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0030_maintenanceprocedure_after_image_and_more'),
    ]

    operations = [
        # Update model options
        migrations.AlterModelOptions(
            name='maintenanceprocedure',
            options={'ordering': ['category', 'frequency', 'name'], 'verbose_name': 'Maintenance Task Template', 'verbose_name_plural': 'Maintenance Task Templates'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'verbose_name': 'Recurring Schedule', 'verbose_name_plural': 'Recurring Schedules'},
        ),
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Preventive Maintenance', 'verbose_name_plural': 'Preventive Maintenance'},
        ),
        
        # Use SQL to safely remove indexes and fields
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS "myappLubd_m_equipme_eedfbd_idx";',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS "myappLubd_m_equipme_d7be07_idx";',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "myappLubd_maintenanceprocedure" DROP COLUMN IF EXISTS equipment_id;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "myappLubd_maintenanceprocedure" DROP COLUMN IF EXISTS after_image;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "myappLubd_maintenanceprocedure" DROP COLUMN IF EXISTS after_image_jpeg_path;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "myappLubd_maintenanceprocedure" DROP COLUMN IF EXISTS before_image;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "myappLubd_maintenanceprocedure" DROP COLUMN IF EXISTS before_image_jpeg_path;',
            reverse_sql='',
        ),
        
        # Add category field safely
        migrations.RunSQL(
            sql='ALTER TABLE "myappLubd_maintenanceprocedure" ADD COLUMN IF NOT EXISTS category VARCHAR(100);',
            reverse_sql='ALTER TABLE "myappLubd_maintenanceprocedure" DROP COLUMN IF EXISTS category;',
        ),
        
        # Update machine_id field
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(blank=True, editable=True, help_text='Unique machine identifier (auto-generated if left empty)', max_length=50, unique=True),
        ),
        
        # Create category index
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "myappLubd_m_categor_14f487_idx" ON "myappLubd_maintenanceprocedure" (category);',
            reverse_sql='DROP INDEX IF EXISTS "myappLubd_m_categor_14f487_idx";',
        ),
    ]
