# Generated by Django 4.2.24 on 2025-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0030_maintenanceprocedure_after_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceprocedure',
            options={'ordering': ['frequency', 'name'], 'verbose_name': 'Maintenance Task Template', 'verbose_name_plural': 'Maintenance Task Templates'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'verbose_name': 'Recurring Schedule', 'verbose_name_plural': 'Recurring Schedules'},
        ),
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Preventive Maintenance', 'verbose_name_plural': 'Preventive Maintenance'},
        ),
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_m_equipme_eedfbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_m_equipme_d7be07_idx',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='after_image_jpeg_path',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='before_image',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='before_image_jpeg_path',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='equipment',
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(blank=True, help_text='Unique machine identifier (auto-generated if left empty)', max_length=50, unique=True),
        ),
    ]
