# Generated by Django 4.2.24 on 2025-11-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0031_remove_equipment_from_maintenance_procedure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceprocedure',
            options={'ordering': ['category', 'frequency', 'name'], 'verbose_name': 'Maintenance Task Template', 'verbose_name_plural': 'Maintenance Task Templates'},
        ),
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='category',
            field=models.CharField(blank=True, help_text='Equipment category this task is typically for (e.g., Fire Pump, HVAC, Elevator)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='maintenanceprocedure',
            index=models.Index(fields=['category'], name='myappLubd_m_categor_14f487_idx'),
        ),
    ]
