# Generated by Django 4.2.24 on 2025-11-16 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def remove_indexes_if_exist(apps, schema_editor):
    """Remove indexes only if they exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        indexes_to_remove = [
            'myappLubd_mp_name_idx',
            'myappLubd_mp_difficulty_idx',
            'myappLubd_mp_created_idx',
        ]
        
        for index_name in indexes_to_remove:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE indexname = %s
                )
            """, [index_name])
            exists = cursor.fetchone()[0]
            if exists:
                cursor.execute(f'DROP INDEX IF EXISTS "{index_name}"')
                print(f"Removed index: {index_name}")


def rename_index_if_exists(apps, schema_editor):
    """Rename index only if it exists"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        old_name = 'myappLubd_mp_category_idx'
        new_name = 'myappLubd_m_categor_14f487_idx'
        
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            )
        """, [old_name])
        exists = cursor.fetchone()[0]
        
        if exists:
            cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
            print(f"Renamed index: {old_name} -> {new_name}")
        else:
            # Check if new name already exists
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE indexname = %s
                )
            """, [new_name])
            if not cursor.fetchone()[0]:
                # Create the index if neither exists
                cursor.execute(f'''
                    CREATE INDEX IF NOT EXISTS "{new_name}" 
                    ON myappLubd_maintenanceprocedure (category)
                ''')
                print(f"Created index: {new_name}")


def remove_fields_if_exist(apps, schema_editor):
    """Remove fields only if they exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        table_name = 'myappLubd_maintenanceprocedure'
        fields_to_remove = [
            'after_image',
            'after_image_jpeg_path',
            'before_image',
            'before_image_jpeg_path',
        ]
        
        for field_name in fields_to_remove:
            # Check if column exists (checking in public schema)
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = %s 
                    AND column_name = %s
                )
            """, [table_name, field_name])
            exists = cursor.fetchone()[0]
            
            if exists:
                cursor.execute(f'ALTER TABLE "{table_name}" DROP COLUMN IF EXISTS "{field_name}"')
                print(f"Removed column: {field_name}")
            else:
                print(f"Column {field_name} does not exist, skipping removal")


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0032_add_category_to_maintenance_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month of consumption (1-12)')),
                ('year', models.IntegerField(default=2025, help_text='Year of consumption')),
                ('totalkwh', models.DecimalField(blank=True, decimal_places=2, help_text='Total kWh consumption', max_digits=10, null=True)),
                ('onpeakkwh', models.DecimalField(blank=True, decimal_places=2, help_text='On-peak kWh consumption', max_digits=10, null=True)),
                ('offpeakkwh', models.DecimalField(blank=True, decimal_places=2, help_text='Off-peak kWh consumption', max_digits=10, null=True)),
                ('totalelectricity', models.DecimalField(blank=True, decimal_places=2, help_text='Total electricity cost', max_digits=10, null=True)),
                ('water', models.DecimalField(blank=True, decimal_places=2, help_text='Water consumption (in cubic meters or units)', max_digits=10, null=True)),
                ('nightsale', models.DecimalField(blank=True, decimal_places=2, help_text='Night sale revenue or consumption', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utility Consumption',
                'verbose_name_plural': 'Utility Consumptions',
                'ordering': ['-year', '-month', 'property', 'room'],
            },
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'verbose_name': 'Recurring Schedule', 'verbose_name_plural': 'Recurring Schedules'},
        ),
        migrations.AlterModelOptions(
            name='preventivemaintenance',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Preventive Maintenance', 'verbose_name_plural': 'Preventive Maintenance'},
        ),
        migrations.RunPython(
            remove_indexes_if_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            rename_index_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            remove_fields_if_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(blank=True, help_text='Unique machine identifier (auto-generated if left empty)', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='utilityconsumption',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_utility_consumptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilityconsumption',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Property associated with this utility consumption record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utility_consumptions', to='myappLubd.property'),
        ),
        migrations.AddField(
            model_name='utilityconsumption',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room associated with this utility consumption record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utility_consumptions', to='myappLubd.room'),
        ),
        migrations.AddIndex(
            model_name='utilityconsumption',
            index=models.Index(fields=['property', 'month', 'year'], name='myappLubd_u_propert_d73a21_idx'),
        ),
        migrations.AddIndex(
            model_name='utilityconsumption',
            index=models.Index(fields=['room', 'month', 'year'], name='myappLubd_u_room_id_bbb8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='utilityconsumption',
            index=models.Index(fields=['year', 'month'], name='myappLubd_u_year_dded39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='utilityconsumption',
            unique_together={('property', 'room', 'month', 'year')},
        ),
    ]
