# Generated by Django 4.2.26 on 2025-11-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0031_alter_maintenanceschedule_options_and_more'),
        ('myappLubd', '0032_add_category_to_maintenance_procedure'),
    ]

    operations = [
    ]
