# Generated by Django 4.2.24 on 2025-11-16 12:54

from django.db import migrations, models


def rename_room_index_if_exists(apps, schema_editor):
    """Rename room index only if it exists"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        old_name = 'myappLubd_u_room_id_bbb8a0_idx'
        new_name = 'myappLubd_u_room_2cee2c_idx'
        
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            )
        """, [old_name])
        exists = cursor.fetchone()[0]
        
        if exists:
            cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
            print(f"Renamed index: {old_name} -> {new_name}")
        else:
            # Check if new name already exists
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE indexname = %s
                )
            """, [new_name])
            if not cursor.fetchone()[0]:
                # Create the index if neither exists
                cursor.execute(f'''
                    CREATE INDEX IF NOT EXISTS "{new_name}" 
                    ON myappLubd_utilityconsumption (room, month, year)
                ''')
                print(f"Created index: {new_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0033_add_utility_consumption'),
    ]

    operations = [
        migrations.RunPython(
            rename_room_index_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='utilityconsumption',
            name='room',
            field=models.IntegerField(blank=True, help_text='Room ID associated with this utility consumption record', null=True),
        ),
    ]
