# Generated by Django 4.2.26 on 2025-11-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0033_merge_20251110_2157'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_mp_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_mp_difficulty_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_mp_created_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceprocedure',
            new_name='myappLubd_m_categor_14f487_idx',
            old_name='myappLubd_mp_category_idx',
        ),
    ]
