# Generated by Django 4.2.24 on 2025-11-16 13:22

from django.db import migrations, connection


def remove_room_index_if_exists(apps, schema_editor):
    """Remove room index only if it exists"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        index_name = 'myappLubd_u_room_id_bbb8a0_idx'
        
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            )
        """, [index_name])
        exists = cursor.fetchone()[0]
        
        if exists:
            cursor.execute(f'DROP INDEX IF EXISTS "{index_name}"')
            print(f"Removed index: {index_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0034_change_room_to_integer'),
    ]

    operations = [
        migrations.RunPython(
            remove_room_index_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='utilityconsumption',
            options={'ordering': ['-year', '-month', 'property'], 'verbose_name': 'Utility Consumption', 'verbose_name_plural': 'Utility Consumptions'},
        ),
        migrations.AlterUniqueTogether(
            name='utilityconsumption',
            unique_together={('property', 'month', 'year')},
        ),
        migrations.RemoveField(
            model_name='utilityconsumption',
            name='room',
        ),
    ]
