# Generated by Django 4.2.26 on 2025-11-16 13:27

from django.db import migrations


def remove_indexes_if_exist(apps, schema_editor):
    """Remove indexes only if they exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        indexes_to_remove = [
            'myappLubd_mp_name_idx',
            'myappLubd_mp_difficulty_idx',
            'myappLubd_mp_created_idx',
            'myappLubd_u_room_id_bbb8a0_idx',
        ]
        
        for index_name in indexes_to_remove:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM pg_indexes 
                    WHERE indexname = %s
                )
            """, [index_name])
            exists = cursor.fetchone()[0]
            if exists:
                cursor.execute(f'DROP INDEX IF EXISTS "{index_name}"')
                print(f"Removed index: {index_name}")
            else:
                print(f"Index {index_name} does not exist, skipping removal")


def rename_index_if_exists(apps, schema_editor):
    """Rename index only if it exists, or create new one if needed"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        old_name = 'myappLubd_mp_category_idx'
        new_name = 'myappLubd_m_categor_14f487_idx'
        
        # Check if old index exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            )
        """, [old_name])
        old_exists = cursor.fetchone()[0]
        
        # Check if new index exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            )
        """, [new_name])
        new_exists = cursor.fetchone()[0]
        
        if old_exists:
            # Old index exists, rename it
            cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
            print(f"Renamed index: {old_name} -> {new_name}")
        elif not new_exists:
            # Neither exists, create the new one
            cursor.execute(f'''
                CREATE INDEX IF NOT EXISTS "{new_name}" 
                ON myappLubd_maintenanceprocedure (category)
            ''')
            print(f"Created index: {new_name}")
        else:
            # New index already exists, nothing to do
            print(f"Index {new_name} already exists, skipping")


def remove_fields_if_exist(apps, schema_editor):
    """Remove fields only if they exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        table_name = 'myappLubd_maintenanceprocedure'
        fields_to_remove = [
            'after_image',
            'after_image_jpeg_path',
            'before_image',
            'before_image_jpeg_path',
        ]
        
        for field_name in fields_to_remove:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_schema = 'public' 
                    AND table_name = %s 
                    AND column_name = %s
                )
            """, [table_name, field_name])
            exists = cursor.fetchone()[0]
            
            if exists:
                cursor.execute(f'ALTER TABLE "{table_name}" DROP COLUMN IF EXISTS "{field_name}"')
                print(f"Removed column: {field_name}")
            else:
                print(f"Column {field_name} does not exist, skipping removal")


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0035_remove_room_from_utility_consumption'),
    ]

    operations = [
        migrations.RunPython(
            remove_indexes_if_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            rename_index_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            remove_fields_if_exist,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
