# Generated by Django 4.2.26 on 2025-11-16 14:21

from django.db import migrations


def noop(apps, schema_editor):
    """No-op function - all operations were already completed in migration 0036"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0036_remove_maintenanceprocedure_myapplubd_mp_name_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            noop,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
