# Generated by Django 4.2.26 on 2025-11-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0036_remove_maintenanceprocedure_myapplubd_mp_name_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_mp_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_mp_difficulty_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_mp_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='utilityconsumption',
            name='myappLubd_u_room_id_bbb8a0_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenanceprocedure',
            new_name='myappLubd_m_categor_14f487_idx',
            old_name='myappLubd_mp_category_idx',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='after_image_jpeg_path',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='before_image',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='before_image_jpeg_path',
        ),
    ]
