# Generated by Django 4.2.26 on 2025-11-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0034_remove_maintenanceprocedure_myapplubd_mp_name_idx_and_more'),
        ('myappLubd', '0037_remove_maintenanceprocedure_myapplubd_mp_name_idx_and_more'),
    ]

    operations = [
    ]
