# Generated by Django 4.2.26 on 2025-11-29 15:20

from django.db import migrations, models
from django.db.migrations.operations.base import Operation


def rename_index_if_exists(apps, schema_editor):
    """Rename index only if it exists"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE indexname = 'myappLubd_mp_category_idx'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER INDEX myappLubd_mp_category_idx 
                RENAME TO myappLubd_m_categor_14f487_idx
            """)


def remove_fields_if_exists(apps, schema_editor):
    """Remove fields only if they exist (DB level)"""
    with schema_editor.connection.cursor() as cursor:
        columns = [
            'after_image',
            'after_image_jpeg_path',
            'before_image',
            'before_image_jpeg_path',
        ]
        for col in columns:
            cursor.execute(f"""
                SELECT 1 FROM information_schema.columns 
                WHERE table_name='myappLubd_maintenanceprocedure' 
                AND column_name='{col}'
            """)
            if cursor.fetchone():
                cursor.execute(
                    f"ALTER TABLE myappLubd_maintenanceprocedure DROP COLUMN {col}"
                )


def remove_indexes_if_exist(apps, schema_editor):
    """Remove indexes only if they exist"""
    with schema_editor.connection.cursor() as cursor:
        indexes_to_remove = [
            'myappLubd_mp_name_idx',
            'myappLubd_mp_difficulty_idx',
            'myappLubd_mp_created_idx',
            'myappLubd_u_room_id_bbb8a0_idx',
        ]
        
        for index_name in indexes_to_remove:
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            """, [index_name])
            if cursor.fetchone():
                cursor.execute(f"DROP INDEX IF EXISTS {index_name}")


def reverse_rename_index_if_exists(apps, schema_editor):
    """Reverse rename index only if it exists"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE indexname = 'myappLubd_m_categor_14f487_idx'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER INDEX myappLubd_m_categor_14f487_idx 
                RENAME TO myappLubd_mp_category_idx
            """)


class RemoveFieldStateOnly(Operation):
    """
    Removes a field from Django's migration state without touching the database.
    Safe to call multiple times because it simply pops the field if present.
    This is needed because migration 0031 may have already removed these fields
    from the state, so we need to handle the case where they don't exist.
    """

    reduces_to_sql = False
    reversible = False

    def __init__(self, model_name, name):
        self.model_name = model_name
        self.name = name
        self.model_name_lower = model_name.lower()

    def state_forwards(self, app_label, state):
        model_key = (app_label, self.model_name_lower)
        model_state = state.models.get(model_key)
        if not model_state:
            return
        # Safely remove field if it exists
        if self.name in model_state.fields:
            model_state.fields.pop(self.name)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Database operations are handled by RunPython above
        pass

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # Not reversible - fields were already removed from database
        pass

    def describe(self):
        return f"State-only removal of field {self.name} from {self.model_name}"


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0037_remove_maintenanceprocedure_myapplubd_mp_name_idx_and_more'),
    ]

    operations = [
        # 1) Remove indexes (DB-level)
        migrations.RunPython(
            remove_indexes_if_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        # 2) Rename index if exists
        migrations.RunPython(
            rename_index_if_exists,
            reverse_code=reverse_rename_index_if_exists,
        ),
        # 3) Remove fields from DB
        migrations.RunPython(
            remove_fields_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),

        # 4) 🔥 Remove fields from Django migration state (important!)
        # Note: Migration 0031 may have already removed these fields from the state,
        # so we use RemoveFieldStateOnly which safely handles the case where fields don't exist
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Database operations already handled by RunPython above
            state_operations=[
                RemoveFieldStateOnly('maintenanceprocedure', 'after_image'),
                RemoveFieldStateOnly('maintenanceprocedure', 'before_image'),
                RemoveFieldStateOnly('maintenanceprocedure', 'after_image_jpeg_path'),
                RemoveFieldStateOnly('maintenanceprocedure', 'before_image_jpeg_path'),
            ],
        ),

        # 5) Add new field machines
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='machines',
            field=models.ManyToManyField(
                blank=True,
                help_text='Machines (Equipment) that use this maintenance procedure template',
                related_name='maintenance_procedures',
                to='myappLubd.machine'
            ),
        ),
    ]
