# Generated by Django 4.2.26 on 2025-11-29 15:20

from django.db import migrations, models


def rename_index_if_exists(apps, schema_editor):
    """Rename index only if it exists"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE indexname = 'myappLubd_mp_category_idx'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER INDEX myappLubd_mp_category_idx 
                RENAME TO myappLubd_m_categor_14f487_idx
            """)


def remove_fields_if_exists(apps, schema_editor):
    """Remove fields only if they exist"""
    with schema_editor.connection.cursor() as cursor:
        # Check and remove after_image
        cursor.execute("""
            SELECT 1 FROM information_schema.columns 
            WHERE table_name='myappLubd_maintenanceprocedure' AND column_name='after_image'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE myappLubd_maintenanceprocedure DROP COLUMN after_image")
        
        # Check and remove after_image_jpeg_path
        cursor.execute("""
            SELECT 1 FROM information_schema.columns 
            WHERE table_name='myappLubd_maintenanceprocedure' AND column_name='after_image_jpeg_path'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE myappLubd_maintenanceprocedure DROP COLUMN after_image_jpeg_path")
        
        # Check and remove before_image
        cursor.execute("""
            SELECT 1 FROM information_schema.columns 
            WHERE table_name='myappLubd_maintenanceprocedure' AND column_name='before_image'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE myappLubd_maintenanceprocedure DROP COLUMN before_image")
        
        # Check and remove before_image_jpeg_path
        cursor.execute("""
            SELECT 1 FROM information_schema.columns 
            WHERE table_name='myappLubd_maintenanceprocedure' AND column_name='before_image_jpeg_path'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE myappLubd_maintenanceprocedure DROP COLUMN before_image_jpeg_path")


def reverse_rename_index_if_exists(apps, schema_editor):
    """Reverse rename index only if it exists"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE indexname = 'myappLubd_m_categor_14f487_idx'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER INDEX myappLubd_m_categor_14f487_idx 
                RENAME TO myappLubd_mp_category_idx
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0037_remove_maintenanceprocedure_myapplubd_mp_name_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_mp_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_mp_difficulty_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenanceprocedure',
            name='myappLubd_mp_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='utilityconsumption',
            name='myappLubd_u_room_id_bbb8a0_idx',
        ),
        migrations.RunPython(
            rename_index_if_exists,
            reverse_code=reverse_rename_index_if_exists,
        ),
        migrations.RunPython(
            remove_fields_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='machines',
            field=models.ManyToManyField(blank=True, help_text='Machines (Equipment) that use this maintenance procedure template', related_name='maintenance_procedures', to='myappLubd.machine'),
        ),
    ]
