# Generated by Django 4.2.26 on 2025-11-29 15:20

from django.db import migrations, models


def rename_index_if_exists(apps, schema_editor):
    """Rename index only if it exists"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE indexname = 'myappLubd_mp_category_idx'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER INDEX myappLubd_mp_category_idx 
                RENAME TO myappLubd_m_categor_14f487_idx
            """)


def remove_fields_if_exists(apps, schema_editor):
    """Remove fields only if they exist (DB level)"""
    with schema_editor.connection.cursor() as cursor:
        columns = [
            'after_image',
            'after_image_jpeg_path',
            'before_image',
            'before_image_jpeg_path',
        ]
        for col in columns:
            cursor.execute(f"""
                SELECT 1 FROM information_schema.columns 
                WHERE table_name='myappLubd_maintenanceprocedure' 
                AND column_name='{col}'
            """)
            if cursor.fetchone():
                cursor.execute(
                    f"ALTER TABLE myappLubd_maintenanceprocedure DROP COLUMN {col}"
                )


def remove_indexes_if_exist(apps, schema_editor):
    """Remove indexes only if they exist"""
    with schema_editor.connection.cursor() as cursor:
        indexes_to_remove = [
            'myappLubd_mp_name_idx',
            'myappLubd_mp_difficulty_idx',
            'myappLubd_mp_created_idx',
            'myappLubd_u_room_id_bbb8a0_idx',
        ]
        
        for index_name in indexes_to_remove:
            cursor.execute("""
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            """, [index_name])
            if cursor.fetchone():
                cursor.execute(f"DROP INDEX IF EXISTS {index_name}")


def reverse_rename_index_if_exists(apps, schema_editor):
    """Reverse rename index only if it exists"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM pg_indexes 
            WHERE indexname = 'myappLubd_m_categor_14f487_idx'
        """)
        if cursor.fetchone():
            cursor.execute("""
                ALTER INDEX myappLubd_m_categor_14f487_idx 
                RENAME TO myappLubd_mp_category_idx
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0037_remove_maintenanceprocedure_myapplubd_mp_name_idx_and_more'),
    ]

    operations = [
        # 1) Remove indexes (DB-level)
        migrations.RunPython(
            remove_indexes_if_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        # 2) Rename index if exists
        migrations.RunPython(
            rename_index_if_exists,
            reverse_code=reverse_rename_index_if_exists,
        ),
        # 3) Remove fields from DB
        migrations.RunPython(
            remove_fields_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),

        # 4) 🔥 Remove fields from Django migration state (important!)
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='after_image',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='before_image',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='after_image_jpeg_path',
        ),
        migrations.RemoveField(
            model_name='maintenanceprocedure',
            name='before_image_jpeg_path',
        ),

        # 5) Add new field machines
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='machines',
            field=models.ManyToManyField(
                blank=True,
                help_text='Machines (Equipment) that use this maintenance procedure template',
                related_name='maintenance_procedures',
                to='myappLubd.machine'
            ),
        ),
    ]
