# Generated by Django 4.2.26 on 2025-11-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0038_remove_maintenanceprocedure_myapplubd_mp_name_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprocedure',
            name='group_id',
            field=models.CharField(blank=True, help_text="Group ID to group related maintenance tasks together (e.g., 'PUMP_MAINTENANCE', 'HVAC_CHECK')", max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='maintenanceprocedure',
            index=models.Index(fields=['group_id'], name='myappLubd_m_group_i_f76158_idx'),
        ),
    ]
