# Generated by Django 4.2.26 on 2025-11-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0039_maintenanceprocedure_group_id_and_more'),
    ]

    operations = [
        # These operations were already handled conditionally in migration 0038
        # We use SeparateDatabaseAndState to update Django's migration state
        # without actually running the database operations again
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='maintenanceprocedure',
                    new_name='myappLubd_m_categor_14f487_idx',
                    old_name='myappLubd_mp_category_idx',
                ),
                migrations.RemoveField(
                    model_name='maintenanceprocedure',
                    name='after_image',
                ),
                migrations.RemoveField(
                    model_name='maintenanceprocedure',
                    name='after_image_jpeg_path',
                ),
                migrations.RemoveField(
                    model_name='maintenanceprocedure',
                    name='before_image',
                ),
                migrations.RemoveField(
                    model_name='maintenanceprocedure',
                    name='before_image_jpeg_path',
                ),
            ],
        ),
    ]
