# Generated by Django 4.2.26 on 2025-11-29 15:32

from django.db import migrations
from django.db.migrations.operations.base import Operation


class RemoveFieldStateOnly(Operation):
    """
    Removes a field from Django's migration state without touching the database.
    Safe to call multiple times because it simply pops the field if present.
    """

    reduces_to_sql = False
    reversible = False

    def __init__(self, model_name, name):
        self.model_name = model_name
        self.name = name

    def state_forwards(self, app_label, state):
        model_key = (app_label, self.model_name.lower())
        model_state = state.models.get(model_key)
        if not model_state:
            return
        model_state.fields.pop(self.name, None)

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Database already handled in earlier migrations; nothing to do here.
        pass

    def describe(self):
        return f"State-only removal of field {self.name} from {self.model_name}"


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0039_maintenanceprocedure_group_id_and_more'),
    ]

    operations = [
        # These operations were already handled conditionally in migration 0038
        # We use SeparateDatabaseAndState to update Django's migration state
        # without actually running the database operations again
        # Note: Field removals (after_image, before_image, etc.) were handled by RunPython
        # in migrations 0036 and 0038, so we don't need to remove them from state here
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='maintenanceprocedure',
                    new_name='myappLubd_m_categor_14f487_idx',
                    old_name='myappLubd_mp_category_idx',
                ),
                RemoveFieldStateOnly('maintenanceprocedure', 'after_image'),
                RemoveFieldStateOnly('maintenanceprocedure', 'after_image_jpeg_path'),
                RemoveFieldStateOnly('maintenanceprocedure', 'before_image'),
                RemoveFieldStateOnly('maintenanceprocedure', 'before_image_jpeg_path'),
            ],
        ),
    ]
