# Generated by Django 4.2.26 on 2025-11-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0039_maintenanceprocedure_group_id_and_more'),
    ]

    operations = [
        # These operations were already handled conditionally in migration 0038
        # We use SeparateDatabaseAndState to update Django's migration state
        # without actually running the database operations again
        # Note: Migration 0038 removed fields from maintenanceprocedure (not preventivemaintenance)
        # The preventivemaintenance fields were never removed and still exist in the model
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='maintenanceprocedure',
                    new_name='myappLubd_m_categor_14f487_idx',
                    old_name='myappLubd_mp_category_idx',
                ),
                # NOTE: The fields after_image, before_image, etc. were removed from maintenanceprocedure
                # in migration 0038, NOT from preventivemaintenance. The preventivemaintenance model
                # still has these fields and they should remain in the migration state.
                # Migration 0046 handles removing these fields from maintenanceprocedure state.
            ],
        ),
    ]
