# Generated by Django 4.2.26 on 2025-11-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0040_rename_myapplubd_mp_category_idx_myapplubd_m_categor_14f487_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='group_id',
            field=models.CharField(blank=True, help_text="Task group ID for this machine (e.g., 'PUMP_MAINTENANCE', 'HVAC_CHECK'). This can also be inherited from linked maintenance procedures.", max_length=100, null=True),
        ),
    ]
