# Generated by Django 4.2.26 on 2025-11-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0041_add_group_id_to_machine'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['group_id'], name='myappLubd_m_group_i_d77154_idx'),
        ),
    ]
