# Generated by Django 4.2.26 on 2025-11-29 16:03

from django.db import migrations, models


def add_index_if_not_exists(apps, schema_editor):
    """Add index only if it doesn't exist"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        index_name = 'myappLubd_m_group_i_d77154_idx'
        
        # Check if index exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes 
                WHERE indexname = %s
            )
        """, [index_name])
        exists = cursor.fetchone()[0]
        
        if not exists:
            # Add the index
            cursor.execute(f"""
                CREATE INDEX "{index_name}" 
                ON myappLubd_machine (group_id)
            """)
            print(f"Created index: {index_name}")
        else:
            print(f"Index {index_name} already exists, skipping")


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0041_add_group_id_to_machine'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_index_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='machine',
                    index=models.Index(fields=['group_id'], name='myappLubd_m_group_i_d77154_idx'),
                ),
            ],
        ),
    ]
