# Generated by Django 4.2.26 on 2025-11-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0042_add_group_id_index_to_machine'),
    ]

    operations = [
        # These operations were already handled conditionally by RunPython in migrations 0036 and 0038
        # We use SeparateDatabaseAndState to update Django's migration state
        # without actually running the database operations again
        # Note: Field removals (after_image, before_image, etc.) were already handled in migration 0040
        # using RemoveFieldStateOnly, so we only need to handle index removals here
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='maintenanceprocedure',
                    name='myappLubd_mp_name_idx',
                ),
                migrations.RemoveIndex(
                    model_name='maintenanceprocedure',
                    name='myappLubd_mp_difficulty_idx',
                ),
                migrations.RemoveIndex(
                    model_name='maintenanceprocedure',
                    name='myappLubd_mp_created_idx',
                ),
                migrations.RemoveIndex(
                    model_name='utilityconsumption',
                    name='myappLubd_u_room_id_bbb8a0_idx',
                ),
            ],
        ),
    ]
