# Generated by Django 4.2.26 on 2025-11-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0038_merge_20251116_2152'),
        ('myappLubd', '0042_add_group_id_index_to_machine'),
    ]

    operations = [
    ]
