# Generated by Django 4.2.26 on 2025-11-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0043_merge_20251130_0042'),
        ('myappLubd', '0043_remove_maintenanceprocedure_myapplubd_mp_name_idx_and_more'),
    ]

    operations = [
    ]
