# Generated by Django 4.2.26 on 2025-11-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0044_ensure_maintenanceprocedure_machines_table'),
        ('myappLubd', '0044_merge_20251130_0838'),
    ]

    operations = [
    ]
