# Generated by Django 4.2.24 on 2025-12-04 04:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
from django.db.migrations.operations.models import CreateModel
import django.db.models.deletion


class CreateModelIfNotExists(CreateModel):
    """CreateModel that checks if table exists before creating"""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        # Construct table name (Django's default format: app_label_modelname)
        # Check options for custom db_table first
        table_name = self.options.get('db_table')
        if not table_name:
            # Use Django's default: app_label + model name (lowercase)
            table_name = f"{app_label}_{self.name.lower()}"
        
        # Check if table exists
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = %s
                )
            """, [table_name])
            exists = cursor.fetchone()[0]
            
            if not exists:
                # Table doesn't exist, create it normally
                super().database_forwards(app_label, schema_editor, from_state, to_state)
            else:
                print(f"Table {table_name} already exists, skipping creation")


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0044_ensure_maintenanceprocedure_machines_table'),
    ]

    operations = [
        CreateModelIfNotExists(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(blank=True, editable=False, help_text='Unique identifier for the inventory item', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Name of the inventory item', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the item', null=True)),
                ('category', models.CharField(choices=[('tools', 'Tools'), ('parts', 'Parts'), ('supplies', 'Supplies'), ('equipment', 'Equipment'), ('consumables', 'Consumables'), ('safety', 'Safety Equipment'), ('other', 'Other')], default='other', help_text='Category of the inventory item', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current quantity in stock')),
                ('min_quantity', models.PositiveIntegerField(default=0, help_text='Minimum quantity threshold for low stock alerts')),
                ('max_quantity', models.PositiveIntegerField(blank=True, default=0, help_text='Maximum quantity capacity', null=True)),
                ('unit', models.CharField(default='pcs', help_text='Unit of measurement (e.g., pcs, kg, liters)', max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price of the item', max_digits=10, null=True)),
                ('location', models.CharField(blank=True, help_text='Storage location of the item', max_length=255, null=True)),
                ('supplier', models.CharField(blank=True, help_text='Supplier or vendor name', max_length=255, null=True)),
                ('supplier_contact', models.CharField(blank=True, help_text='Supplier contact information', max_length=255, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('reserved', 'Reserved'), ('maintenance', 'Under Maintenance')], default='available', help_text='Current status of the item', max_length=20)),
                ('last_restocked', models.DateTimeField(blank=True, help_text='Date when item was last restocked', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date if applicable', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this inventory item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='Property associated with this inventory item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='myappLubd.property')),
                ('room', models.ForeignKey(blank=True, help_text='Room where the item is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='myappLubd.room')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['item_id'], name='myappLubd_i_item_id_a18ab3_idx'), models.Index(fields=['category', 'status'], name='myappLubd_i_categor_76da04_idx'), models.Index(fields=['property', 'status'], name='myappLubd_i_propert_fd3fc4_idx'), models.Index(fields=['status'], name='myappLubd_i_status_ffab93_idx')],
            },
        ),
    ]
