# Generated by Django 4.2.24 on 2025-12-04 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0047_restore_preventivemaintenance_image_fields_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Job associated with this inventory item usage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='myappLubd.job'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='preventive_maintenance',
            field=models.ForeignKey(blank=True, help_text='Preventive maintenance task associated with this inventory item usage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='myappLubd.preventivemaintenance'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['job'], name='myappLubd_i_job_id_50f920_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['preventive_maintenance'], name='myappLubd_i_prevent_37662d_idx'),
        ),
    ]
