# Generated by Django 4.2.16 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0049_add_image_to_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='If False, user will not receive email notifications (summary emails, etc.)'),
        ),
    ]

