# Generated by Django 4.2.26 on 2025-12-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0045_merge_20251130_1500'),
        ('myappLubd', '0049_add_image_to_inventory'),
    ]

    operations = [
    ]
