# Generated by Django 4.2.26 on 2025-12-08 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0050_add_email_notifications_enabled'),
        ('myappLubd', '0050_merge_20251204_1524'),
    ]

    operations = [
    ]
