# Generated by Django 4.2 on 2025-12-25
# Add supplier field to WorkspaceReport model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0053_add_workspace_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacereport',
            name='supplier',
            field=models.CharField(
                blank=True,
                help_text='Supplier or vendor name',
                max_length=255,
                null=True,
            ),
        ),
    ]
