# Generated by Django 4.2.27 on 2025-12-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0054_add_supplier_to_workspace_report'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventory',
            name='myappLubd_i_job_id_50f920_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='myappLubd_i_prevent_37662d_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_report__24d4e2_idx',
            old_name='myappLubd_w_report__b5c123_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_status_0b0a76_idx',
            old_name='myappLubd_w_status_a1d234_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_priorit_e5570c_idx',
            old_name='myappLubd_w_priorit_c2e345_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_propert_d23739_idx',
            old_name='myappLubd_w_propert_d3f456_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_topic_i_12ef12_idx',
            old_name='myappLubd_w_topic_i_e4g567_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_created_5f0b39_idx',
            old_name='myappLubd_w_created_f5h678_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_report__15af70_idx',
            old_name='myappLubd_w_report__g6i789_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_created_9bc621_idx',
            old_name='myappLubd_w_created_h7j890_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_status_bb2d20_idx',
            old_name='myappLubd_w_status__i8k901_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacereport',
            new_name='myappLubd_w_propert_504cd7_idx',
            old_name='myappLubd_w_propert_j9l012_idx',
        ),
    ]
