# Generated by Django 4.2.27 on 2025-12-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0055_add_workspace_report_images_5_to_15'),
        ('myappLubd', '0055_remove_inventory_myapplubd_i_job_id_50f920_idx_and_more'),
    ]

    operations = [
    ]
