# Generated by Django 4.2.27 on 2026-01-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0056_add_electricity_cost_budget_to_utility_consumption'),
        ('myappLubd', '0056_merge_20251225_1632'),
    ]

    operations = [
    ]
