# Generated by Django 4.2.27 on 2026-01-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0057_add_user_uses_roster'),
        ('myappLubd', '0057_merge_20260115_1005'),
    ]

    operations = [
    ]
