# Generated by Django 4.2.27 on 2026-01-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0058_merge_20260119_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilityconsumption',
            name='year',
            field=models.IntegerField(default=2026, help_text='Year of consumption'),
        ),
    ]
