# Generated by Django 4.2
# Fix migration to ensure the 'image' column exists on myappLubd_machine table
# This migration fixes the issue where the column may be missing from the database

import django.core.validators
from django.db import migrations, models


def add_image_column_if_missing(apps, schema_editor):
    """
    Safely add the image column to myappLubd_machine table if it doesn't exist.
    This handles cases where the migration state and database are out of sync.
    """
    connection = schema_editor.connection
    table_name = 'myappLubd_machine'
    column_name = 'image'
    
    with connection.cursor() as cursor:
        # Check if the column exists in PostgreSQL
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name = %s 
            AND column_name = %s
        """, [table_name, column_name])
        
        exists = cursor.fetchone() is not None
        
        if not exists:
            # Add the column - ImageField uses VARCHAR(100) in PostgreSQL
            cursor.execute(f'''
                ALTER TABLE "{table_name}" 
                ADD COLUMN "{column_name}" VARCHAR(100) NULL
            ''')
            print(f"Successfully added '{column_name}' column to {table_name}")
        else:
            print(f"Column '{column_name}' already exists in {table_name}, no action needed")


def noop(apps, schema_editor):
    """No-op for reverse migration - we don't want to drop the column."""
    pass


class Migration(migrations.Migration):
    """
    This migration ensures the 'image' column exists on the Machine model.
    
    It uses RunPython to check for the column existence and add it if missing,
    which is safer than relying on Django's state tracking.
    """

    dependencies = [
        ('myappLubd', '0059_add_image_to_machine'),
    ]

    operations = [
        migrations.RunPython(
            add_image_column_if_missing,
            reverse_code=noop,
        ),
    ]
