# Generated by Django 4.2.27 on 2026-01-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0058_add_roster_leave'),
        ('myappLubd', '0059_alter_utilityconsumption_year'),
    ]

    operations = [
    ]
