# Generated by Django 4.2.27 on 2026-01-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0059_add_image_to_machine'),
        ('myappLubd', '0060_merge_20260120_1618'),
    ]

    operations = [
    ]
