# Generated by Django 4.2.30 on 2026-04-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myappLubd", "0061_merge_20260127_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="is_visible_in_create_job",
            field=models.BooleanField(
                default=True,
                help_text="Controls whether this topic appears in Create Job topic list on frontend",
            ),
        ),
    ]
