# Generated by Django 5.2.14 on 2026-06-14 06:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0065_subscriptionplan_tenant_tenantmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(choices=[('job', 'Work Order'), ('preventive_maintenance', 'Preventive Maintenance'), ('manual', 'Manual Adjustment')], default='manual', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='asset_tag',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='expected_replacement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='lifecycle_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date this asset was purchased', null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='replacement_cost_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['expected_replacement_date'], name='myappLubd_m_expecte_cc2284_idx'),
        ),
        migrations.AddIndex(
            model_name='machine',
            index=models.Index(fields=['warranty_end_date'], name='myappLubd_m_warrant_a8e8ce_idx'),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='consumed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_usage_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='myappLubd.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_usage_records', to='myappLubd.job'),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='preventive_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_usage_records', to='myappLubd.preventivemaintenance'),
        ),
        migrations.AddField(
            model_name='inventoryusage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_usage_records', to='myappLubd.property'),
        ),
        migrations.AddIndex(
            model_name='inventoryusage',
            index=models.Index(fields=['inventory', 'consumed_at'], name='myappLubd_i_invento_ad39ff_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryusage',
            index=models.Index(fields=['property', 'consumed_at'], name='myappLubd_i_propert_fff069_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryusage',
            index=models.Index(fields=['job'], name='myappLubd_i_job_id_183ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryusage',
            index=models.Index(fields=['preventive_maintenance'], name='myappLubd_i_prevent_f053fc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryusage',
            index=models.Index(fields=['source', 'consumed_at'], name='myappLubd_i_source_36d724_idx'),
        ),
    ]
