# Generated by Django 4.2.30 on 2026-06-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0066_inventoryusage_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='area',
            new_name='myappLubd_a_propert_6ae795_idx',
            old_name='myappLubd_a_propert_idx',
        ),
        migrations.RenameIndex(
            model_name='area',
            new_name='myappLubd_a_name_47621f_idx',
            old_name='myappLubd_a_name_idx',
        ),
        migrations.RenameIndex(
            model_name='jobcomment',
            new_name='myappLubd_j_job_id_d27ab5_idx',
            old_name='myappLubd_j_job_idx',
        ),
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='myappLubd_p_user_id_471004_idx',
            old_name='myappLubd_p_user_id_2c6c80_idx',
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
