# Generated by Django 5.2.14 on 2026-06-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0067_rename_myapplubd_a_propert_idx_myapplubd_a_propert_6ae795_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Asia/Bangkok', max_length=64),
        ),
    ]
