# Generated by Django 4.2.30 on 2026-07-15 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myappLubd", "0069_remove_roster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Uploaded image file",
                null=True,
                upload_to="maintenance_job_images/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif", "webp"]
                    )
                ],
            ),
        ),
    ]
