# Generated by Django 4.2.30 on 2026-08-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0071_pm_master_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='myappLubd.property'),
        ),
    ]
