# Generated by Django 4.2.30 on 2026-08-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0073_alter_job_property_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canonical_rooms', to='myappLubd.property'),
        ),
    ]
