# Generated by Django 4.2.30 on 2026-08-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0074_room_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_rooms', to='myappLubd.property'),
        ),
    ]
