# Generated by Django 4.2.30 on 2026-08-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0075_alter_room_property_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='properties',
        ),
    ]
