# Generated by Django 4.2.30 on 2026-08-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0076_remove_room_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='properties',
        ),
    ]
