# Generated by Django 4.2.30 on 2026-08-27 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0078_preventive_maintenance_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=512)),
                ('email_at_link', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='auth_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Auth identities',
                'ordering': ['issuer', 'subject'],
                'indexes': [models.Index(fields=['user'], name='auth_identity_user_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='authidentity',
            constraint=models.UniqueConstraint(fields=('issuer', 'subject'), name='unique_auth_identity_issuer_subject'),
        ),
    ]
