# Generated by Django 4.2.30 on 2026-09-03 07:07

from django.db import migrations, models
import django.db.models.deletion


DEFAULT_CATEGORIES = (
    ('tools', 'Tools', 10),
    ('parts', 'Parts', 20),
    ('supplies', 'Supplies', 30),
    ('equipment', 'Equipment', 40),
    ('consumables', 'Consumables', 50),
    ('safety_equipment', 'Safety Equipment', 60),
    ('other', 'Other', 70),
)
DEFAULT_NAMES = {code: name for code, name, _sort_order in DEFAULT_CATEGORIES}
DEFAULT_SORT_ORDERS = {code: sort_order for code, _name, sort_order in DEFAULT_CATEGORIES}


def flush_deferred_constraints(schema_editor):
    """Allow subsequent ALTER TABLE operations after FK-affecting updates."""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('SET CONSTRAINTS ALL IMMEDIATE')


def forwards_inventory_categories(apps, schema_editor):
    """Create tenant categories and attach every inventory row without dropping data."""
    db_alias = schema_editor.connection.alias
    Tenant = apps.get_model('myappLubd', 'Tenant')
    Inventory = apps.get_model('myappLubd', 'Inventory')
    InventoryCategory = apps.get_model('myappLubd', 'InventoryCategory')

    pending_defaults = []
    for tenant_id in Tenant.objects.using(db_alias).values_list('pk', flat=True).iterator():
        pending_defaults.extend(
            InventoryCategory(
                tenant_id=tenant_id,
                code=code,
                name=name,
                sort_order=sort_order,
            )
            for code, name, sort_order in DEFAULT_CATEGORIES
        )
        if len(pending_defaults) >= 3500:
            InventoryCategory.objects.using(db_alias).bulk_create(
                pending_defaults, batch_size=3500
            )
            pending_defaults = []
    if pending_defaults:
        InventoryCategory.objects.using(db_alias).bulk_create(
            pending_defaults, batch_size=3500
        )

    category_groups = list(
        Inventory.objects.using(db_alias)
        .values_list('category_legacy', 'property__tenant_id')
        .distinct()
    )
    categories_by_scope = {
        (tenant_id, code): pk
        for pk, tenant_id, code in InventoryCategory.objects.using(db_alias).values_list(
            'pk', 'tenant_id', 'code'
        )
    }
    for raw_legacy_code, tenant_id in category_groups:
        legacy_code = raw_legacy_code if raw_legacy_code not in (None, '') else 'other'
        canonical_code = 'safety_equipment' if legacy_code == 'safety' else legacy_code
        default_name = DEFAULT_NAMES.get(canonical_code)
        if default_name is None:
            default_name = legacy_code.replace('_', ' ').replace('-', ' ').strip().title()
        category_id = categories_by_scope.get((tenant_id, canonical_code))
        if category_id is None:
            category = InventoryCategory.objects.using(db_alias).create(
                tenant_id=tenant_id,
                code=canonical_code,
                name=default_name[:100] or 'Other',
                sort_order=DEFAULT_SORT_ORDERS.get(canonical_code, 70),
            )
            category_id = category.pk
            categories_by_scope[(tenant_id, canonical_code)] = category_id
        Inventory.objects.using(db_alias).filter(
            category_legacy=raw_legacy_code,
            property__tenant_id=tenant_id,
        ).update(category_id=category_id)

    if Inventory.objects.using(db_alias).filter(category_id__isnull=True).exists():
        raise RuntimeError('Inventory category migration left one or more rows unmapped.')
    flush_deferred_constraints(schema_editor)


def backwards_inventory_categories(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Inventory = apps.get_model('myappLubd', 'Inventory')
    InventoryCategory = apps.get_model('myappLubd', 'InventoryCategory')
    for category in InventoryCategory.objects.using(db_alias).only('pk', 'code').iterator():
        legacy_code = 'safety' if category.code == 'safety_equipment' else category.code
        Inventory.objects.using(db_alias).filter(category_id=category.pk).update(
            category_legacy=legacy_code
        )
    flush_deferred_constraints(schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0083_stripe_billing_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='myappLubd_i_categor_76da04_idx',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='category',
            new_name='category_legacy',
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Owning tenant. Blank is reserved for migrated unscoped inventory.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='myappLubd.tenant'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the inventory item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='myappLubd.inventorycategory'),
        ),
        migrations.RunPython(forwards_inventory_categories, backwards_inventory_categories),
        migrations.RemoveField(
            model_name='inventory',
            name='category_legacy',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(help_text='Category of the inventory item', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='myappLubd.inventorycategory'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['category', 'status'], name='myappLubd_i_categor_fdfa67_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycategory',
            index=models.Index(fields=['tenant', 'is_active', 'sort_order'], name='myappLubd_i_tenant__d69b95_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'code'), name='unique_inventory_category_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('code',), name='unique_unscoped_inventory_category_code'),
        ),
    ]
