# Generated by Django 4.2.30 on 2026-09-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappLubd', '0084_inventory_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='line_destination_id',
            field=models.CharField(blank=True, help_text='LINE Messaging API user, group, or room destination ID.', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='line_notifications_enabled',
            field=models.BooleanField(default=False, help_text="Send Job event alerts to this Property's LINE destination."),
        ),
    ]
